### ISSUE TITLE
SetStringByOffset broken & blocksize off by one

### ISSUE THREAD

**Issue by BotoX** [ntoxin66/Dynamic#12]
Native_Dynamic_SetStringByOffset sets the string to an empty string, quiet obvious issue if you look at Native_Dynamic_SetString which is a few lines above it.
Fix:
```diff
diff --git a/scripting/dynamic/system/natives.sp b/scripting/dynamic/system/natives.sp
index a64ade4..1af3589 100644
--- a/scripting/dynamic/system/natives.sp
+++ b/scripting/dynamic/system/natives.sp
@@ -376,11 +376,11 @@ public int Native_Dynamic_SetStringByOffset(Handle plugin, int params)
 {
 	DynamicObject dynamic = GetNativeCell(1);
 	DynamicOffset offset = GetNativeCell(2);
-	int length = GetNativeCell(4);
-	char[] value = new char[length];
-	GetNativeString(3, value, length);
 	int valuelength;
 	GetNativeStringLength(3, valuelength);
+	char[] value = new char[++valuelength];
+	GetNativeString(3, value, valuelength);
+	int length = GetNativeCell(4);
 	return _Dynamic_SetStringByOffset(dynamic, offset, value, length, valuelength);
 }
 ```

When you want to insert 3 ints, you'd set the blocksize to 3, right?
Well guess what you need 4 because index 0 is not used/reserved, did not investigate enough.
I just did the following for now:
 ```diff
diff --git a/scripting/dynamic.sp b/scripting/dynamic.sp
index 9956ca3..86bbe53 100644
--- a/scripting/dynamic.sp
+++ b/scripting/dynamic.sp
@@ -144,6 +144,8 @@ stock int _Dynamic_Initialise(Handle plugin, int blocksize=64, int startsize=0,
 	if (index == -1)
 		member = DynamicObject();
 	
+	blocksize++;
+	
 	// Initial 
 	member.Initialise(plugin, blocksize, startsize, persistent);
 	
```
You should probably know better why index 0 is not used.

**Comment by ntoxin66** [comment]
Please dont combine multiple issues together.

Dynamic strings are working via offsets. You can run sm_dynamic_selftest to test for member get/set failures.

Each int member type requires two blocks. The first block represents a type  (Dynamic is type safe) the following block(s) represent the members value.

In a Dynamic objects internal array, block 0 stores the global index of itself for reverse lookups.

Do not edit Dynamic.

**Comment by BotoX** [comment]
It is definitely not working....

// native bool Dynamic_SetStringByOffset(Dynamic obj, int offset, const char[] value, int length=0);
length = 0, okay?

```C
int length = GetNativeCell(4);
char[] value = new char[length];
GetNativeString(3, value, length);
```
Well geeee what happens here?
Making a char array with size zero and copying a string into it with maxlength = 0

Are you still so confident it is working?

And about the 2nd issue, maybe you should clarify that in the docs/classbuilder how to calculate the blocksize instead of just setting it to 64 without further comment.

**Comment by BotoX** [comment]
Oh, the selftest doesn't even use SetStringByOffset, it is only used in the classbuilder and class example..

**Comment by ntoxin66** [comment]
0 means it's the members length is based on the input string size

**Comment by ntoxin66** [comment]
I could make the class builder set the blocksize

**Comment by ntoxin66** [comment]
I'll look into string by offset soon

**Comment by ntoxin66** [comment]
https://github.com/ntoxin66/Dynamic/commit/2d301ad30914b9624513ff755d366afa2a70e047

Added selftest and fixed bug.

Thanking you BotoX.
